reward:
  model: openai-community/gpt2
  datasets_path:
    - data/descriptiveness_offline_5k.json
  batch_size: 32
  epochs: 3

lm:
  model: openai-community/gpt2
  datasets_path:
    - data/descriptiveness_offline_5k.json
  batch_size: 16
  epochs: 5
  ppo:
    learning_rate: 1.4e-5
    max_grad_norm: 0.5
    target_kl: 0.1
    init_kl_coef: 0.2
    response_length_min: 32
    response_length_max: 96