reward:
  model: openai-community/gpt2
  datasets_path: data/descriptiveness_offline_5k
  # - data/cnndm_offline_60k
  # - data/cnndm_online_45k
  # - data/descriptiveness_offline_5k
  # - data/sentimen_offline_5k
  # - data/tldr_offline_60k
  # - data/tldr_online_45k
  test_size: 0.2
  batch_size: 32
  epochs: 5
  warmup_steps: 500
  weight_decay: 0.01
  lr: 0.00001

lm:
  model: openai-community/gpt2
  datasets_path: data/descriptiveness_offline_5k
    # - data/cnndm_offline_60k
    # - data/cnndm_online_45k
    # - data/descriptiveness_offline_5k
    # - data/sentimen_offline_5k
    # - data/tldr_offline_60k
    # - data/tldr_online_45k
  batch_size: 8
  epochs: 10_000
  num_envs: 2
  response_max_len: 96
  gamma: 0.99
  ppo:
    kl_coef: 0.2